server:
  port: 82
spring:
  application:
    name: gatway
  cloud:
    inetutils:
      ignored-interfaces: eth.*
    nacos:
      discovery:
        #        server-addr: 101.132.132.173:8848
        server-addr: localhost:8848
        namespace: ced286b3-fe72-48fe-a610-894506540b1e
    #        ip: 49.234.239.138
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: staff-consumer
          uri: lb://staffScanInformation-provider
          predicates:
            - Path=/staff/**


