server:
  port: 7500

spring:
  #邮件配置
  profiles:
    active: dev

  messages:
    basename: ValidationMessages
    encoding: utf-8

management:
  endpoints:
    web:
      exposure:
        include: '*'